"""initial schema with world hierarchy

Revision ID: 0192d56dad6e
Revises:
Create Date: 2025-11-20 03:20:13.208757

"""

from typing import Sequence, Union
from pgvector.sqlalchemy import Vector
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0192d56dad6e"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "game_worlds",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "professions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("base_salary", sa.Integer(), nullable=False),
        sa.Column("education_required", sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "cities",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("world_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["world_id"],
            ["game_worlds.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "neighborhoods",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "average_social_class",
            sa.Enum("low", "medium", "high", name="socialclassdbenum"),
            nullable=False,
        ),
        sa.Column("average_cost_of_living", sa.Integer(), nullable=False),
        sa.Column("city_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["city_id"],
            ["cities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "houses",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("address", sa.String(length=255), nullable=True),
        sa.Column("neighborhood_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["neighborhood_id"],
            ["neighborhoods.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "rooms",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("room_type", sa.String(length=50), nullable=False),
        sa.Column("house_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["house_id"],
            ["houses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sims",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("personality_summary", sa.Text(), nullable=True),
        sa.Column("world_id", sa.UUID(), nullable=False),
        sa.Column("current_location_room_id", sa.UUID(), nullable=True),
        sa.Column("parent_a_id", sa.UUID(), nullable=True),
        sa.Column("parent_b_id", sa.UUID(), nullable=True),
        sa.Column("age_in_days", sa.Integer(), nullable=False),
        sa.Column("life_stage", sa.String(length=50), nullable=False),
        sa.Column("is_alive", sa.Boolean(), nullable=False),
        sa.Column("death_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("profession_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["current_location_room_id"],
            ["rooms.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_a_id"],
            ["sims.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_b_id"],
            ["sims.id"],
        ),
        sa.ForeignKeyConstraint(
            ["profession_id"],
            ["professions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["world_id"],
            ["game_worlds.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "world_objects",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("object_type", sa.String(length=50), nullable=False),
        sa.Column("room_id", sa.UUID(), nullable=False),
        sa.Column("state", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["rooms.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "action_log",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column("timestamp", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("actor_sim_id", sa.UUID(), nullable=False),
        sa.Column("action_type", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("target_sim_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["actor_sim_id"],
            ["sims.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_sim_id"],
            ["sims.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "memories",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("sim_id", sa.UUID(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("importance_score", sa.Integer(), nullable=False),
        sa.Column("embedding", Vector(dim=768), nullable=True),
        sa.ForeignKeyConstraint(
            ["sim_id"],
            ["sims.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "relationships",
        sa.Column("sim_a_id", sa.UUID(), nullable=False),
        sa.Column("sim_b_id", sa.UUID(), nullable=False),
        sa.Column("relationship_score", sa.Integer(), nullable=False),
        sa.Column("romance_score", sa.Integer(), nullable=False),
        sa.Column("commitment_level", sa.String(length=50), nullable=True),
        sa.CheckConstraint("sim_a_id < sim_b_id"),
        sa.ForeignKeyConstraint(
            ["sim_a_id"],
            ["sims.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sim_b_id"],
            ["sims.id"],
        ),
        sa.PrimaryKeyConstraint("sim_a_id", "sim_b_id"),
    )
    op.create_table(
        "sim_needs",
        sa.Column("sim_id", sa.UUID(), nullable=False),
        sa.Column("hunger", sa.Integer(), nullable=False),
        sa.Column("energy", sa.Integer(), nullable=False),
        sa.Column("social", sa.Integer(), nullable=False),
        sa.Column("hygiene", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["sim_id"],
            ["sims.id"],
        ),
        sa.PrimaryKeyConstraint("sim_id"),
    )
    op.create_table(
        "sim_status",
        sa.Column("sim_id", sa.UUID(), nullable=False),
        sa.Column("current_feeling", sa.String(length=50), nullable=True),
        sa.Column("current_action", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["sim_id"],
            ["sims.id"],
        ),
        sa.PrimaryKeyConstraint("sim_id"),
    )
    op.create_table(
        "skills",
        sa.Column("sim_id", sa.UUID(), nullable=False),
        sa.Column("skill_name", sa.String(length=50), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["sim_id"],
            ["sims.id"],
        ),
        sa.PrimaryKeyConstraint("sim_id", "skill_name"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("skills")
    op.drop_table("sim_status")
    op.drop_table("sim_needs")
    op.drop_table("relationships")
    op.drop_table("memories")
    op.drop_table("action_log")
    op.drop_table("world_objects")
    op.drop_table("sims")
    op.drop_table("rooms")
    op.drop_table("houses")
    op.drop_table("neighborhoods")
    op.drop_table("cities")
    op.drop_table("professions")
    op.drop_table("game_worlds")
    # ### end Alembic commands ###
