"""add action log table

Revision ID: 62b3536b6359
Revises: ffec2aeb91b3
Create Date: 2025-11-06 11:05:50.146814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62b3536b6359'
down_revision: Union[str, Sequence[str], None] = 'ffec2aeb91b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_log',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('actor_sim_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_sim_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['actor_sim_id'], ['sims.id'], ),
    sa.ForeignKeyConstraint(['target_sim_id'], ['sims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('action_log')
    # ### end Alembic commands ###
