"""add profession module and link to sims

Revision ID: 809f72ba1499
Revises: 62b3536b6359
Create Date: 2025-11-15 02:09:54.938491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '809f72ba1499'
down_revision: Union[str, Sequence[str], None] = '62b3536b6359'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('base_salary', sa.Integer(), nullable=False),
    sa.Column('education_required', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('sims', sa.Column('profession_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'sims', 'professions', ['profession_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sims', type_='foreignkey')
    op.drop_column('sims', 'profession_id')
    op.drop_table('professions')
    # ### end Alembic commands ###
