"""create initial simulation schema

Revision ID: ffec2aeb91b3
Revises:
Create Date: 2025-10-29 13:27:56.070355

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = "ffec2aeb91b3"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    op.create_table(
        "sims",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("personality_summary", sa.Text(), nullable=True),
        sa.Column("parent_a_id", sa.UUID(), nullable=True),
        sa.Column("parent_b_id", sa.UUID(), nullable=True),
        sa.Column("age_in_days", sa.Integer(), nullable=False),
        sa.Column("life_stage", sa.String(length=50), nullable=False),
        sa.Column("is_alive", sa.Boolean(), nullable=False),
        sa.Column("death_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_a_id"],
            ["sims.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_b_id"],
            ["sims.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "memories",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("sim_id", sa.UUID(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("importance_score", sa.Integer(), nullable=False),
        sa.Column("embedding", Vector(dim=768), nullable=True),
        sa.ForeignKeyConstraint(
            ["sim_id"],
            ["sims.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "relationships",
        sa.Column("sim_a_id", sa.UUID(), nullable=False),
        sa.Column("sim_b_id", sa.UUID(), nullable=False),
        sa.Column("relationship_score", sa.Integer(), nullable=False),
        sa.Column("romance_score", sa.Integer(), nullable=False),
        sa.Column("commitment_level", sa.String(length=50), nullable=True),
        sa.CheckConstraint("sim_a_id < sim_b_id"),
        sa.ForeignKeyConstraint(
            ["sim_a_id"],
            ["sims.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sim_b_id"],
            ["sims.id"],
        ),
        sa.PrimaryKeyConstraint("sim_a_id", "sim_b_id"),
    )
    op.create_table(
        "sim_needs",
        sa.Column("sim_id", sa.UUID(), nullable=False),
        sa.Column("hunger", sa.Integer(), nullable=False),
        sa.Column("energy", sa.Integer(), nullable=False),
        sa.Column("social", sa.Integer(), nullable=False),
        sa.Column("hygiene", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["sim_id"],
            ["sims.id"],
        ),
        sa.PrimaryKeyConstraint("sim_id"),
    )
    op.create_table(
        "sim_status",
        sa.Column("sim_id", sa.UUID(), nullable=False),
        sa.Column("current_feeling", sa.String(length=50), nullable=True),
        sa.Column("current_action", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["sim_id"],
            ["sims.id"],
        ),
        sa.PrimaryKeyConstraint("sim_id"),
    )
    op.create_table(
        "skills",
        sa.Column("sim_id", sa.UUID(), nullable=False),
        sa.Column("skill_name", sa.String(length=50), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["sim_id"],
            ["sims.id"],
        ),
        sa.PrimaryKeyConstraint("sim_id", "skill_name"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("skills")
    op.drop_table("sim_status")
    op.drop_table("sim_needs")
    op.drop_table("relationships")
    op.drop_table("memories")
    op.drop_table("sims")
    op.execute("DROP EXTENSION IF EXISTS vector;")
    # ### end Alembic commands ###
